### ISSUE TITLE
Error when trying to start the react-native package server 

### ISSUE THREAD

**Issue by ramsestom** [aksonov/react-native-xmpp#13]
When executing "react-native start" inside  XmppDemo, I end up with this error:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn sh ENOENT
    at exports._errnoException (util.js:873:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3
```

other react-native projects are just working fine so it doesn't seem to be an issue with my react-native installation but rather an issue with this specific project.

**Comment by aksonov** [comment]
Demo was VERY old (based on React Native 0.12), now it should work with latest react native, please check

**Comment by Froelund** [comment]
@ramsestom I'll close this issue as no response. Please submit a new issue if the problem persists.
